### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by craigfearon** [mblackford/BlackfordTwilioBundle#1]
Hi there, this may be an issue with the actual Twillio SDK looking at how little code your bundle actually has to go wrong. 

**PHP Version:** 7.0

**ERROR:** 
`
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                                                 
  PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/apcu.so' - /usr/lib/php/20160303/apcu.so: undefined symbol: php_var_unserialize_init in Unknown on line 0                
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to ProxyManager\Generator\Util\ProxiedMethodReturnExpression::generate() must be an instance of ProxyManager\Generator\Util\ReflectionMethod, instance of Zend\Code\Reflection\MethodReflection given, called in /site/vendor/ocramius/proxy-manager/src/ProxyManager  
  /ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php on line 72 in /site/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/Pro  
  xiedMethodReturnExpression.php:33                                                                                                                                                                         
  Stack trace:                                                                                                                                                                                              
  #0 /site/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php(72): ProxyManager\Generator\Ut  
  il\ProxiedMethodReturnExpression::generate('$this->valueHol...', Object(Zend\Code\Reflection\MethodReflection))                                                                                           
  #1 /site/vendor/ocramius/proxy-manager/src/ProxyManager/ in /site/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/ProxiedMethodRetur  
  nExpression.php on line 33     
`

I have added the bundle to the composer json and to the AppKernel etc but when I try the composer update I receive the above error and when I try to clear cache I receive the following error:

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to ProxyManager\Generator\Util\ProxiedMethodReturnExpression::generate() must be an instance of ProxyManager\Generator\Util\ReflectionMethod, instance of Zend\Code\Reflection\MethodReflection given, called in /site/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php on line 72 in /site/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/ProxiedMethodReturnExpression.php:33
`

And when viewing the frontend I receive the following error:

`Type error: Return value of ProxyManager\Configuration::setGeneratorStrategy() must be an instance of ProxyManager\void, none returned
`

Any input would be greatly appreciated! 

Thanks,
Craig

**Comment by mblackford** [comment]
Hi Craig,

I had a look through your stack trace, and it appears to be related to the Ocramius Proxy Manager, rather than the Twilio bundle. To make sure, try removing the Twilio bundle by running:

`composer remove blackford/twilio-bundle`

My guess is that you'll still get the error when clearing your cache. Let me know how that goes!
